name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What mod version were you using?
      options:
        - 1.0.0
        - 1.1.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Skyrim-Version
    attributes:
      label: What Skyrim version are you using?
      multiple: false
      options:
        - 1.5.97
        - 1.6.640
        - 1.6.1130
        - 1.6.1170
        - Other
  - type: input
    id: other-version
    attributes:
      label: "If 'Other', please specify below:"
      description: Specify the version number here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/master/CONDUCT).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
