name: Update Issue Template on Release

on:
  release:
    types: [published]

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Issue Template
        run: |
          # Custom script to update the issue template
          # with the new version from the release tag
          .github/scripts/update-template-script.sh

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/ISSUE_TEMPLATE/bug_report.yml
          git commit -m "Update issue template with new release version"
          git push
